name: 'Новый шаблон'
file_path: 'app/lib/templates/template_1.docx'
mapping:
  'номер акта': 'num_act'
  'дата составления': 'date_compilation'
  'основание для проведения технической экспертизы': 'basis_tech_examination'
  'инн': 'in'
  'кпп': 'kpp'
  'заказчик': 'customer'
  'адрес проведения контроля': 'control_address'
  'изделие': 'item'
  'инвентарный номер': 'inventory_number'
  'дата изготовления': 'production_date'
  'балансовая стоимость': 'balance_cost'
  'диагностика': 'diagnostics'
  'вывод': 'output'
  'экономическое обоснование': 'economic_justification'
  'заключение': 'conclusion'
  'примечание': 'notice'
  'директор': 'director'
  'эксперт': 'expert'
